- name: install git
  apt: update_cache=yes name=git state=latest
- name: add teamspeak user
  user: name=ts3 state=present

- name: creating teamspeak database
  mysql_db: name=teamspeak3 state=present

- name: creating teamspeak database user
  mysql_user: name=teamspeak3 password={{ teamspeak_db_password }} priv=teamspeak3.*:ALL state=present

- name: checking out ts3 scripts
  git: repo=https://github.com/Maesto/teamspeak3-helperScripts.git dest=/home/ts3/teamspeak3-helperScripts/ update=yes 

- name: config scripts
  copy: src=config dest=/home/ts3/teamspeak3-helperScripts/opt/config owner=ts3 group=ts3 mode=0640
